### ISSUE TITLE
📝 Request 테이블 정규화

### ISSUE THREAD

**Issue by jaeuk520** [TravelMate-KU/TravelMate-Server#15]
## 📝 Issue
`Travel_Component` 테이블의 `name` 애트리뷰트도 `Request` 테이블의 속성값으로 추가하는 것이 어떤가요!

Volunteer가 disabled들의 request를 조회하면 현재 아래의 값들이 조회되어야 합니다.
- disabled 이름
- 요청 타입 (ex. Transportation)
- 여행 요소 이름 (ex. KTX)
- 시작 시간
- 종료 시간

이 때 `여행 요소 이름`을 조회하기 위해서 `Course`, `Course_Travel_Component`, `Travel_Component` 총 3개의 테이블이 추가로 조인되어야 하는데 이보다 차라리 `여행 요소 이름` 값이 중복되더라도 Request 테이블에 포함하는 것이 테이블 간의 결합도를 줄일 수 있어 괜찮을 것 같습니다.

**Comment by david-parkk** [comment]
동의합니다. 그러면 단일 요청의 경우애는(ex Room하나만 신청) Room 에 해당하는 name 값들 모두 넣는 것이 맞나요?

**Comment by jaeuk520** [comment]
엇 저희 원래 저번에는 어떤 식으로 보여줬었나요..?

**Comment by david-parkk** [comment]
저번 기준으로는 해당 단일 요청에 대한 모든 값들을 보여줘야 했었는데, 그렇게 구현이 되지 않았고, 가장 상단 값만 보여주었습니다

**Comment by david-parkk** [comment]
오 좋습니다, 여행 type도  따로 보이게 되어 있어서 상관없을 것 같습니다!
