### ISSUE TITLE
레포 권한 요청

### ISSUE THREAD

**Issue by david-parkk** [TravelMate-KU/TravelMate-Server#2]
**해당 레포 push가 안됩니다 ㅠㅜ**

![image](https://github.com/TravelMate-KU/TravelMate-Server/assets/57484954/e0151fc5-6572-4005-ae96-13951135307f)

**origin 주소 재설정 이후에도 안되서 권한 확인 부탁드립니다.**

**Comment by david-parkk** [comment]
디스코드 웹훅연동하려고 하는데 혹시 그것도 부탁 드리겠습니다 (웹훅을 만들어 주시거나, 제가 레포 setting에 들어갈 수 있어야 합니다)

**Comment by jaeuk520** [comment]
프로젝트 권한 `owner`로 변경해두었습니다!
